[verify]
verify_trust = true

[trust]
trust_anchors = """
-----BEGIN CERTIFICATE-----
MIICRDCCAeqgAwIBAgIUZqFG+bWoAD6eMMbTXmV8XZBFG6swCgYIKoZIzj0EAwIw
bjELMAkGA1UEBhMCTVgxDzANBgNVBAgMBlNvbm9yYTETMBEGA1UEBwwKSGVybW9z
aWxsbzEZMBcGA1UECgwQRU0tQXVkaW8gVGVzdCBDQTEeMBwGA1UEAwwVRU0tQXVk
aW8gVGVzdCBSb290IENBMB4XDTI2MDgxOTA4MTcxN1oXDTM2MDgxNjA4MTcxN1ow
bjELMAkGA1UEBhMCTVgxDzANBgNVBAgMBlNvbm9yYTETMBEGA1UEBwwKSGVybW9z
aWxsbzEZMBcGA1UECgwQRU0tQXVkaW8gVGVzdCBDQTEeMBwGA1UEAwwVRU0tQXVk
aW8gVGVzdCBSb290IENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEX7bvoLeY
l/TRt8UKj9uhYuTojkZN6vlc94pBD0Aeg3Zpv+TenSMalwRy7zDJlxd67ghfC2iQ
PO+hiVzckE0EfqNmMGQwHQYDVR0OBBYEFD/yUogMt301ZND/m4ay+yCgmY9dMB8G
A1UdIwQYMBaAFD/yUogMt301ZND/m4ay+yCgmY9dMBIGA1UdEwEB/wQIMAYBAf8C
AQAwDgYDVR0PAQH/BAQDAgEGMAoGCCqGSM49BAMCA0gAMEUCIBCmsZ8N5i4PrHQD
aWOnPml9gCXiwo6yoySPZqfePA1BAiEA3sBy0W9nokOwxtERueLh+XKbVf6EysF7
B0Ak1syWivE=
-----END CERTIFICATE-----
"""
trust_config = "1.3.6.1.5.5.7.3.4"
